### ISSUE TITLE
Entrar com ID da Sala não funciona

### ISSUE THREAD

**Issue by rfxbtw** [Lucas8x/stopots-bot#2]
Quando seleciona a opção de entrar com ID da sala, o bot não funciona

ID: 22718
Entrando...
Traceback (most recent call last):
  File "stopots_bot.py", line 583, in <module>
    join_game(username)
  File "stopots_bot.py", line 265, in join_game
    wait.until(ec.presence_of_element_located((By.XPATH, Game.username_input)))
  File "C:\Users\Rafael\Desktop\stopots-bot-master\python\lib\site-packages\selenium\webdriver\support\wait.py", line 80, in until
    raise TimeoutException(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message:

**Comment by Lucas8x** [comment]
Vou corrigir em breve xD

**Comment by rfxbtw** [comment]
foi corrigido? eu gostaria do seu contato para propostas xd

**Comment by Lucas8x** [comment]
Foi
